using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XrmPath.UmbracoCore.Models.Definitions
{
    public static class UmbracoCustomLookups
    {
        //content uniqueIds
        public static readonly string AutoGeneratedRedirects = "autogeneratedRedirects";
        public static readonly string ErrorPage = "errorPage";
        public static readonly string SearchPage = "searchPage";
        public static readonly string HomePage = "homePage";
        public static readonly string TestPages = "testPages";

        //unique urls
        public static readonly string MyProfilePage = "/profile";

        //authentication pages uniqueIds
        public static readonly string LoginPage = "loginPage";
        public static readonly string LogoutPage = "logoutPage";
        public static readonly string SignupPage = "signupPage";
        public static readonly string MyAccountPage = "myaccountPage";
        public static readonly string ForgotPasswordPage = "forgotpasswordPage";
        public static readonly string ChangePasswordPage = "changepasswordPage";
        public static readonly string VerifyAccountPage = "verifyaccountPage";
        public static readonly string NoAccessPage = "noaccessPage";

        //email template uniqueIds
        public static readonly string DefaultEmailTemplate = "emailTemplateDefaultTemplate";
        public static readonly string ForgotPasswordEmailTemplate = "emailTemplateForgotPassword";
        public static readonly string SignUpEmailTemplate = "emailTemplateSignUp";

        //member groups
        public static readonly string WebsiteUser = "Website User";
    }
}
